import React, { useState } from 'react';
import { uploadCSV } from '../api/predictionService';

const CSVUploadPage = () => {
  const [file, setFile] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [message, setMessage] = useState('');
  const [trainingResults, setTrainingResults] = useState(null);

  const handleFileChange = (e) => {
    setFile(e.target.files[0]);
    setMessage('');
    setTrainingResults(null);
  };

  const handleUpload = async () => {
    if (!file) {
      setMessage('Please select a file first');
      return;
    }

    setUploading(true);
    setMessage('');
    setTrainingResults(null);

    try {
      const response = await uploadCSV(file);
      setMessage('File uploaded and model trained successfully!');
      // In a real application, you would fetch the actual training results
      setTrainingResults({
        r2: 0.85,
        rmse: 2.3,
        mae: 1.8
      });
    } catch (error) {
      console.error('Upload error:', error);
      setMessage('Error uploading file: ' + (error.response?.data || error.message));
    } finally {
      setUploading(false);
    }
  };

  return (
    <div>
      <h1 className="text-3xl font-bold mb-6">CSV Upload</h1>
      
      <div className="bg-white p-6 rounded-lg shadow mb-6">
        <h2 className="text-xl font-semibold mb-4">Upload Dataset</h2>
        <div className="mb-4">
          <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="csv-file">
            Select CSV File
          </label>
          <input
            type="file"
            id="csv-file"
            accept=".csv"
            onChange={handleFileChange}
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          />
        </div>
        <button
          onClick={handleUpload}
          disabled={uploading || !file}
          className={`bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline ${
            uploading || !file ? 'opacity-50 cursor-not-allowed' : ''
          }`}
        >
          {uploading ? 'Uploading...' : 'Upload and Train Model'}
        </button>
        {message && (
          <div className={`mt-4 p-3 rounded ${message.includes('Error') ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-700'}`}>
            {message}
          </div>
        )}
      </div>

      {trainingResults && (
        <div className="bg-white p-6 rounded-lg shadow">
          <h2 className="text-xl font-semibold mb-4">Training Results</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-blue-50 p-4 rounded">
              <h3 className="font-semibold text-blue-800">R² Score</h3>
              <p className="text-2xl font-bold">{trainingResults.r2.toFixed(2)}</p>
            </div>
            <div className="bg-green-50 p-4 rounded">
              <h3 className="font-semibold text-green-800">RMSE</h3>
              <p className="text-2xl font-bold">{trainingResults.rmse.toFixed(2)}</p>
            </div>
            <div className="bg-purple-50 p-4 rounded">
              <h3 className="font-semibold text-purple-800">MAE</h3>
              <p className="text-2xl font-bold">{trainingResults.mae.toFixed(2)}</p>
            </div>
          </div>
        </div>
      )}

      <div className="bg-white p-6 rounded-lg shadow mt-6">
        <h2 className="text-xl font-semibold mb-4">Required CSV Format</h2>
        <p className="mb-2">The CSV file should contain the following columns:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>request_id</li>
          <li>origin_lat</li>
          <li>origin_lng</li>
          <li>dest_lat</li>
          <li>dest_lng</li>
          <li>distance</li>
          <li>time_of_day</li>
          <li>vehicle_id</li>
          <li>battery_level</li>
          <li>speed</li>
          <li>trip_time</li>
        </ul>
        <p className="mt-4 text-sm text-gray-600">
          Note: traffic_index and weather fields are auto-generated by the system when processing ride requests.
        </p>
      </div>
    </div>
  );
};

export default CSVUploadPage;