package com.neurofleetx.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDateTime;

@Entity
@Table(name = "ride_request")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class RideRequest {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    private double originLat;
    
    private double originLng;
    
    private double destLat;
    
    private double destLng;
    
    private double trafficIndex;  // Auto-generated by system (0.0 to 1.0)
    
    private String weather;       // Auto-generated by system (sunny, cloudy, rainy, snowy)
    
    private String timeOfDay;     // Auto-generated by system (morning, afternoon, evening, night)
    
    private double eta;
    
    private double earnings; // Earnings for the driver
    
    private LocalDateTime timestamp;
    
    @Enumerated(EnumType.STRING)
    private RideStatus status = RideStatus.PENDING; // Default status is PENDING
    
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;
    
    @ManyToOne
    @JoinColumn(name = "taxi_id")
    private Taxi taxi;


    public enum RideStatus {
        PENDING, ASSIGNED, IN_PROGRESS, COMPLETED
    }
    
    @PrePersist
    protected void onCreate() {
        if (timestamp == null) {
            timestamp = LocalDateTime.now();
        }
        // Set default status if not set
        if (status == null) {
            status = RideStatus.PENDING;
        }
    }
}